theme = "space-villain"
icons = "awesome"
scrolling = "natural"

[[block]]
block = "net"
format = "{ssid} {signal_strength}"
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {used}/{total}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}"
clickable = false

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]

[[block]]
block = "sound"
step_width = 2
headphones_indicator = true

[[block]]
block = "backlight"
invert_icons = true

[[block]]
block = "time"
